---
title: "2016 SOI Analysis"
output: html_notebook
---



```{r setup, include = FALSE}

knitr::opts_chunk$set(cache = TRUE)
library(tidyverse)
library(ggplot2)
library(maps)
library(sparklyr)
```




Configuring Spark Server
```{r}
conf <- spark_config()
conf$`spark.memory.fraction` <- 0.9
conf$`sparklyr.shell.driver-memory` <- "4G"
conf$spark.dynamicAllocation.enabled="true"
sc <- spark_connect(master = "local", config = conf)
```

Loading Data
```{r}
soi_data <- spark_read_csv(sc, "soi_data",  "../data/2016_SOI.csv")
zip_to_county <- spark_read_csv(sc, "zip_to_county", "../data/zip_code_to_county_mapping.csv")
```

Calculating Statistics
```{r}
transformed_data <- soi_data %>% 
    filter(zipcode != 0) %>% 
    left_join(zip_to_county, by = c("zipcode" = "zip_code", "STATE" = "state")) %>% 
    filter(!is.na(county)) %>% 
    select(STATE, county, zipcode, agi_stub, N1) %>% 
    group_by(STATE, county, agi_stub) %>%
    summarise(county_n = sum(N1, na.rm = TRUE)) %>% 
    group_by(STATE, county) %>% 
    mutate(county_total = sum(county_n, na.rm = TRUE), county_percent = 100 * county_n/county_total) %>% 
    arrange(STATE, county, agi_stub) %>% 
    select(STATE,county, agi_stub, county_n, county_percent) %>% 
    mutate(county = tolower(county)) %>% 
    collect()
```

Plotting
```{r}
usa_data <- map_data(map = "usa")
state_data <- map_data(map = "state")
county_data <- map_data(map = "county") %>% 
    left_join(transformed_data, by = c("subregion" = "county"))
ggplot(data = usa_data, mapping = aes(x = long, y = lat,  group = group)) +
    geom_polygon(data = filter(county_data, agi_stub == 1), aes(fill = county_percent), color = "white") + 
    geom_polygon(data = state_data, fill = "NA", color = "black") +
    geom_polygon(fill = NA, color = "black") +
    coord_fixed()

ggplot(data = usa_data, mapping = aes(x = long, y = lat,  group = group)) +
    geom_polygon(data = filter(county_data, agi_stub == 2), aes(fill = county_percent), color = "white") + 
    geom_polygon(data = state_data, fill = "NA", color = "black") +
    geom_polygon(fill = NA, color = "black") +
    coord_fixed()


ggplot(data = usa_data, mapping = aes(x = long, y = lat,  group = group)) +
    geom_polygon(data = filter(county_data, agi_stub == 3), aes(fill = county_percent), color = "white") + 
    geom_polygon(data = state_data, fill = "NA", color = "black") +
    geom_polygon(fill = NA, color = "black") +
    coord_fixed()

ggplot(data = usa_data, mapping = aes(x = long, y = lat,  group = group)) +
    geom_polygon(data = filter(county_data, agi_stub == 4), aes(fill = county_percent), color = "white") + 
    geom_polygon(data = state_data, fill = "NA", color = "black") +
    geom_polygon(fill = NA, color = "black") +
    coord_fixed()

ggplot(data = usa_data, mapping = aes(x = long, y = lat,  group = group)) +
    geom_polygon(data = filter(county_data, agi_stub == 5), aes(fill = county_percent), color = "white") + 
    geom_polygon(data = state_data, fill = "NA", color = "black") +
    geom_polygon(fill = NA, color = "black") +
    coord_fixed()

ggplot(data = usa_data, mapping = aes(x = long, y = lat,  group = group)) +
    geom_polygon(data = filter(county_data, agi_stub == 6), aes(fill = county_percent), color = "white") + 
    geom_polygon(data = state_data, fill = "NA", color = "black") +
    geom_polygon(fill = NA, color = "black") +
    coord_fixed()
```

